In [1]:
import numpy as np

#DataTypes and Attribute

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1, 2, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [4]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a3.shape

(2, 3, 3)

In [7]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [8]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [9]:
a1.size, a2.size, a3.size

(3, 6, 18)

#Pandas Using Numpy

In [10]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

#Array Creations

In [11]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
start, stop, step = 0, 10, 2
range_array = np.arange(start, stop, step)
range_array

array([0, 2, 4, 6, 8])

In [14]:
start, stop = 0, 10
random_array = np.random.randint(start,stop, size=(3,5))
random_array

array([[8, 9, 3, 5, 4],
       [2, 8, 9, 3, 8],
       [1, 3, 2, 3, 6]])

In [15]:
random_between_01 = np.random.random((5,3))
random_between_01

array([[0.48365904, 0.19632094, 0.39465465],
       [0.23997412, 0.41905889, 0.215291  ],
       [0.84796052, 0.8843762 , 0.02314379],
       [0.34467696, 0.9215453 , 0.3951746 ],
       [0.08470707, 0.30196218, 0.14008746]])

In [16]:
random_between_01_2 = np.random.rand(5,3)
random_between_01_2

array([[0.20212469, 0.30447239, 0.18553195],
       [0.38529215, 0.0653794 , 0.64211245],
       [0.76958977, 0.33388807, 0.67897285],
       [0.61346496, 0.43525299, 0.74646975],
       [0.33818045, 0.29993691, 0.26573563]])

#Pseudo Random Number

In [17]:
whatever_value = 54
np.random.seed(whatever_value)
random_array_2 = np.random.randint(10, size=(5,3))
random_array_2

array([[5, 2, 7],
       [1, 0, 8],
       [7, 1, 9],
       [6, 9, 7],
       [4, 4, 4]])

#Viewing Arrays

In [18]:
random_array_2

array([[5, 2, 7],
       [1, 0, 8],
       [7, 1, 9],
       [6, 9, 7],
       [4, 4, 4]])

In [19]:
np.unique(random_array_2)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [20]:
a1

array([1, 2, 3])

In [21]:
a1[0]

1

In [22]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [23]:
a2[0]

array([1. , 2. , 3.3])

In [24]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
#print first 2 elements of al rows
a3[:,:,:2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

In [27]:
#print last value of every row
a3[:,:,-1]

array([[ 3,  6,  9],
       [12, 15, 18]])

In [28]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 4, 0, 6, 8],
         [9, 7, 3, 2, 1],
         [2, 6, 9, 8, 1],
         [7, 7, 2, 7, 7]],

        [[8, 3, 3, 5, 7],
         [8, 3, 5, 8, 1],
         [3, 2, 2, 8, 2],
         [3, 9, 9, 9, 9]],

        [[3, 5, 4, 5, 4],
         [4, 8, 3, 0, 2],
         [0, 1, 4, 6, 6],
         [3, 5, 0, 4, 9]]],


       [[[3, 8, 1, 1, 3],
         [8, 2, 6, 2, 6],
         [0, 5, 2, 5, 7],
         [7, 4, 0, 6, 5]],

        [[6, 4, 6, 0, 5],
         [8, 7, 7, 2, 5],
         [4, 5, 9, 9, 9],
         [3, 6, 8, 8, 9]],

        [[9, 3, 8, 0, 4],
         [6, 2, 5, 7, 3],
         [8, 2, 5, 4, 8],
         [2, 9, 9, 9, 5]]]])

In [29]:
# get first 4 numbers of inner most arrays
a4[:,:,:,:4]

array([[[[6, 4, 0, 6],
         [9, 7, 3, 2],
         [2, 6, 9, 8],
         [7, 7, 2, 7]],

        [[8, 3, 3, 5],
         [8, 3, 5, 8],
         [3, 2, 2, 8],
         [3, 9, 9, 9]],

        [[3, 5, 4, 5],
         [4, 8, 3, 0],
         [0, 1, 4, 6],
         [3, 5, 0, 4]]],


       [[[3, 8, 1, 1],
         [8, 2, 6, 2],
         [0, 5, 2, 5],
         [7, 4, 0, 6]],

        [[6, 4, 6, 0],
         [8, 7, 7, 2],
         [4, 5, 9, 9],
         [3, 6, 8, 8]],

        [[9, 3, 8, 0],
         [6, 2, 5, 7],
         [8, 2, 5, 4],
         [2, 9, 9, 9]]]])

#Manipulating Array

Arithmatic

In [30]:
a1

array([1, 2, 3])

In [31]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [32]:
a1 + ones

array([2., 3., 4.])

In [33]:
a1 - ones

array([0., 1., 2.])

In [34]:
a1 * ones

array([1., 2., 3.])

In [35]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [36]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [37]:
a1/ones

array([1., 2., 3.])

In [38]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [39]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [40]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [41]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

#Aggrigation

In [42]:
massive_array = np.random.random(100000)
massive_array.shape

(100000,)

In [43]:
%timeit sum(massive_array) # python's builtin sum function
%timeit np.sum(massive_array) # numpy's sum

9.94 ms ± 2.79 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
42.8 µs ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [44]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [45]:
np.max(a2), np.min(a2)

(6.5, 1.0)

In [46]:
np.mean(a2)

3.6333333333333333

In [47]:
'Standard Daviation',  np.std(a2)

('Standard Daviation', 1.8226964152656422)

In [48]:
'Variation', np.var(a2)

('Variation', 3.3222222222222224)

#Reshape

In [49]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [50]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [51]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [52]:
a2_reshaped = a2.reshape(2,3,1)

In [53]:
a2_reshaped * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

#Transpose

In [54]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [55]:
a2.shape

(2, 3)

In [56]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [57]:
a2.T.shape

(3, 2)

In [58]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [59]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [60]:
a3.T.shape

(3, 3, 2)

#Dot Product

In [61]:
np.random.seed(0)

In [62]:
met1 = np.random.randint(10, size=(5,3))
met2 = np.random.randint(10, size=(5,3))
met1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [63]:
met2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [64]:
met1.shape, met2.shape

((5, 3), (5, 3))

In [65]:
np.multiply(met1, met2) # met1 * met2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [66]:
met2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [67]:
res = np.dot(met1, met2.T)
res

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [68]:
res.shape

(5, 5)

#Nut Butter Example

In [69]:
np.random.seed(0)
sales = np.random.randint(20, size = (5, 3))
sales

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [77]:
weekly_sales = pd.DataFrame(sales, index = ['Mon', 'Tues', 'Wed', 'Thurs', 'Fri'],
                            columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [79]:
price = np.array([10, 8, 12])
price

array([10,  8, 12])

In [87]:
price.shape

(3,)

In [92]:
price.reshape(1,3)

array([[10,  8, 12]])

In [93]:
butter_price = pd.DataFrame(price.reshape(1,3), index = ['Price'], 
                            columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
butter_price

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [119]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [120]:
butter_price.shape

(1, 3)

In [121]:
weekly_sales.T

Mon  Tues  Wed  Thurs  Fri
Almond Butter   12     3    9      4    1
Peanut Butter   15     3   19      6    6
Cashew Butter    0     7   18     12    7

In [124]:
total_sales = butter_price.dot(weekly_sales.T)
total_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [125]:
total_sales.shape

(1, 5)

In [127]:
weekly_sales['Total Sales'] = total_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Sales
Mon               12             15              0          240
Tues               3              3              7          138
Wed                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142

#Comparision of Arrays

In [136]:
a1

array([1, 2, 3])

In [137]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [139]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [140]:
a1 == a1

array([ True,  True,  True])

In [141]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [142]:
a1 >= 3

array([False, False,  True])

#Sorting Arrays

In [151]:
random_array5 = np.random.randint(10, size = (3,5))
random_array5

array([[1, 7, 9, 9, 3],
       [6, 7, 2, 0, 3],
       [5, 9, 4, 4, 6]])

In [152]:
np.sort(random_array5)

array([[1, 3, 7, 9, 9],
       [0, 2, 3, 6, 7],
       [4, 4, 5, 6, 9]])

In [153]:
np.argsort(random_array5) # return the original indices of element after sorted

array([[0, 4, 1, 2, 3],
       [3, 2, 4, 0, 1],
       [2, 3, 0, 4, 1]])

In [156]:
random_array5

array([[1, 7, 9, 9, 3],
       [6, 7, 2, 0, 3],
       [5, 9, 4, 4, 6]])

In [154]:
np.argmin(random_array5) # return index of smallest element from entire array

8

In [155]:
np.argmax(random_array5)  # return index of largest element from entire array

2

In [158]:
np.argmin(random_array5, axis=0)  # return index of smallest element in each column.

array([0, 0, 1, 1, 0])

In [159]:
np.argmax(random_array5, axis=1)   # return index of largest element in each row.

array([2, 1, 1])

#Practical Example of Images

In [ ]:
from matplotlib.image import imread

panda_image = imread("panda.png") 

In [6]:
# the image is 2330 pixels tall and 3500 pixels wide
panda_image.size, panda_image.shape, panda_image.ndim

(24465000, (2330, 3500, 3), 3)

In [18]:
# RGB value of first pixel of image
panda_image[:2]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)