In [14]:
import numpy as np

p = np.array([ [1,7], [2,1], [3,2] ])
print("p :",p)

q = np.array([ [1,1], [1,-1], [1,0] ])
print("q :",q)

# addition
c = np.add(p,q);
print("addition :", c)

r = np.array([ [1,3,1], [1,0,1] ])
print("r :", r)

# multiplication
d = np.dot(p, r)
print("multiplication of p and r :", d)

# determinent
det = np.linalg.det(d)
print("determinent of d is", det)

# inverse
m = np.array([ [1,-1], [2,3] ])
print("inverse of m : ", np.linalg.inv(m))

p : [[1 7]
 [2 1]
 [3 2]]
q : [[ 1  1]
 [ 1 -1]
 [ 1  0]]
addition : [[2 8]
 [3 0]
 [4 2]]
r : [[1 3 1]
 [1 0 1]]
multiplication of p and r : [[8 3 8]
 [3 6 3]
 [5 9 5]]
determinent of d is 0.0
inverse of m :  [[ 0.6  0.2]
 [-0.4  0.2]]
