In [42]:
import numpy as np

np.random.seed(0)

# X = [[1, 2, 3, 2.5],
#      [2.0, 5.0, -1.0, 2.0],
#      [-1.5, 2.7, 3.3, -0.8]]


#class for feedforward without activation function

class layer_dense:
  def __init__(self, n_input, n_neuron):  #neurons of hidden layer
    self.weights = 0.10 * np.random.randn(n_input, n_neuron)
    self.bias = np.zeros((1,n_neuron))
  
  def forward(self, input):
    self.output = np.dot(input, self.weights) + self.bias





In [43]:
# Activation Functions

class Activation_ReLU:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)


class Activation_SoftMax:
  def forward(self, inputs):
    temp = inputs - np.max(inputs, axis=1, keepdims=True)
    exp_values = np.exp(temp)
    probability = exp_values / np.sum(exp_values, axis=1, keepdims=True)
    self.output = probability


In [44]:
# loss function

class Loss:
  def calculate(self, output, y):
    sample_loss = self.forward(output, y)
    data_loss = np.mean(sample_loss)
    return sample_loss



class Loss_CategoricalCrossEntropy(Loss):
  def forward(self, y_pred, y_true):
    samples = len(y_pred)
    y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)

    if len(y_true.shape) == 1:
      correct_confidence = y_pred_clipped[range(samples), y_true]

    elif len(y_true.shape) == 2:
      correct_confidence = np.sum(y_pred_clipped * y_true, axis = 1)
      
    negative_log_likelihood = - np.log(correct_confidence)
    return negative_log_likelihood




In [45]:
# spiral data creation

def create_data(points, classes):
  N = points
  D = 2
  K = classes
  X = np.zeros((N*K,D)) 
  y = np.zeros(N*K, dtype='uint8') 
  for j in range(K):
    ix = range(N*j,N*(j+1))
    r = np.linspace(0.0,1,N) # radius
    t = np.linspace(j*4,(j+1)*4,N) + np.random.randn(N)*0.2 # theta
    X[ix] = np.c_[r*np.sin(t), r*np.cos(t)]
    y[ix] = j
  return X,y


import matplotlib.pyplot as plt

X, y = create_data(100,3)

# plt.scatter(X[:, 0], X[:, 1], c=y, s=40, cmap=plt.cm.Spectral)
# plt.show()



dense1 = layer_dense(2, 3)
activation1 = Activation_ReLU()

dense2 = layer_dense(3, 3)
activation2 = Activation_SoftMax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print("\nPredicted values")
print(activation2.output[:5])

print("\nActual class of each point")
print(y)

loss_function = Loss_CategoricalCrossEntropy()
loss = loss_function.calculate(activation2.output, y)

print("\nLoss is ")
print(loss[:5])



Predicted values
[[0.33333333 0.33333333 0.33333333]
 [0.33332113 0.33332188 0.33335699]
 [0.33330232 0.33330422 0.33339346]
 [0.33327144 0.33327524 0.33345332]
 [0.33325287 0.33325781 0.33348932]]

Actual class of each point
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2]

Loss is 
[1.09861229 1.0986489  1.09870534 1.09879799 1.09885372]


In [56]:
my = np.array([1,2,3])

mytemp = my.copy()

mytemp[2] = 100

print(mytemp.base)

None
